class CreatePouchslots < ActiveRecord::Migration[5.2]
  def change
    create_table :pouchslots do |t|
      t.integer :pouchtype1_id, default: 1
      t.integer :free1, default: 0
      t.integer :member1, default: 0
      t.integer :pouchtype2_id, default: 1
      t.integer :free2, default: 0
      t.integer :member2, default: 0
      t.integer :pouchtype3_id, default: 1
      t.integer :free3, default: 0
      t.integer :member3, default: 0
      t.integer :pouchtype4_id, default: 1
      t.integer :free4, default: 0
      t.integer :member4, default: 0
      t.integer :pouchtype5_id, default: 1
      t.integer :free5, default: 0
      t.integer :member5, default: 0
      t.integer :pouchtype6_id, default: 1
      t.integer :free6, default: 0
      t.integer :member6, default: 0
      t.integer :pouchtype7_id, default: 1
      t.integer :free7, default: 0
      t.integer :member7, default: 0
      t.integer :pouchtype8_id, default: 1
      t.integer :free8, default: 0
      t.integer :member8, default: 0
      t.integer :pouchtype9_id, default: 1
      t.integer :free9, default:0
      t.integer :member9, default: 0
      t.integer :pouchtype10_id, default: 1
      t.integer :free10, default: 0
      t.integer :member10, default: 0
      t.integer :pouchtype11_id, default: 1
      t.integer :free11, default: 0
      t.integer :member11, default: 0
      t.integer :pouchtype12_id, default: 1
      t.integer :free12, default: 0
      t.integer :member12, default: 0
      t.integer :pouchtype13_id, default: 1
      t.integer :free13, default: 0
      t.integer :member13, default: 0
      t.integer :pouchtype14_id, default: 1
      t.integer :free14, default: 0
      t.integer :member14, default: 0
      t.integer :pouchtype15_id, default: 1
      t.integer :free15, default: 0
      t.integer :member15, default: 0
      t.integer :pouchtype16_id, default: 1
      t.integer :free16, default: 0
      t.integer :member16, default: 0
      t.integer :pouchtype17_id, default: 1
      t.integer :free17, default: 0
      t.integer :member17, default: 0
      t.integer :pouchtype18_id, default: 1
      t.integer :free18, default: 0
      t.integer :member18, default: 0
      t.integer :pouchtype19_id, default: 1
      t.integer :free19, default: 0
      t.integer :member19, default: 0
      t.integer :pouchtype20_id, default: 1
      t.integer :free20, default: 0
      t.integer :member20, default: 0
      t.integer :pouchtype21_id, default: 1
      t.integer :free21, default: 0
      t.integer :member21, default: 0
      t.integer :pouchtype22_id, default: 1
      t.integer :free22, default: 0
      t.integer :member22, default: 0
      t.integer :pouchtype23_id, default: 1
      t.integer :free23, default: 0
      t.integer :member23, default: 0
      t.integer :pouchtype24_id, default: 1
      t.integer :free24, default: 0
      t.integer :member24, default: 0
      t.integer :pouchtype25_id, default: 1
      t.integer :free25, default: 0
      t.integer :member25, default: 0
      t.integer :pouchtype26_id, default: 1
      t.integer :free26, default: 0
      t.integer :member26, default: 0
      t.integer :pouchtype27_id, default: 1
      t.integer :free27, default: 0
      t.integer :member27, default: 0
      t.integer :pouchtype28_id, default: 1
      t.integer :free28, default: 0
      t.integer :member28, default: 0
      t.integer :pouchtype29_id, default: 1
      t.integer :free29, default: 0
      t.integer :member29, default: 0
      t.integer :pouchtype30_id, default: 1
      t.integer :free30, default: 0
      t.integer :member30, default: 0
      t.integer :pouchtype31_id, default: 1
      t.integer :free31, default: 0
      t.integer :member31, default: 0
      t.integer :pouchtype32_id, default: 1
      t.integer :free32, default: 0
      t.integer :member32, default: 0
      t.integer :pouchtype33_id, default: 1
      t.integer :free33, default: 0
      t.integer :member33, default: 0
      t.integer :pouchtype34_id, default: 1
      t.integer :free34, default: 0
      t.integer :member34, default: 0
      t.integer :pouchtype35_id, default: 1
      t.integer :free35, default: 0
      t.integer :member35, default: 0
      t.integer :pouchtype36_id, default: 1
      t.integer :free36, default: 0
      t.integer :member36, default: 0
      t.integer :pouchtype37_id, default: 1
      t.integer :free37, default: 0
      t.integer :member37, default: 0
      t.integer :pouchtype38_id, default: 1
      t.integer :free38, default: 0
      t.integer :member38, default: 0
      t.integer :pouchtype39_id, default: 1
      t.integer :free39, default: 0
      t.integer :member39, default: 0
      t.integer :pouchtype40_id, default: 1
      t.integer :free40, default: 0
      t.integer :member40, default: 0
      t.integer :pouchtype41_id, default: 1
      t.integer :free41, default: 0
      t.integer :member41, default: 0
      t.integer :pouchtype42_id, default: 1
      t.integer :free42, default: 0
      t.integer :member42, default: 0
      t.integer :pouch_id

      t.timestamps
    end
  end
end
